workflows:
  ios-release:
    name: iOS Release Build
    environment:
      flutter: stable
    scripts:
      - name: Set up certificate and provisioning profile
        script: |
          mkdir -p ~/certificates
          echo "$IOS_CERTIFICATE" | base64 --decode > ~/certificates/ios_cert.p12
          security create-keychain -p "$KEYCHAIN_PASSWORD" build.keychain
          security import ~/certificates/ios_cert.p12 -k ~/Library/Keychains/build.keychain
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" ~/Library/Keychains/build.keychain
      - name: Build iOS Release
        script: |
          flutter clean
          flutter pub get
          flutter build ios --release --no-codesign
    publish:
      ios:
        artifact: build/ios/ipa/Runner.ipa
